version: '3.8'

services:
  whisper:
    image: onerahmet/openai-whisper-asr-webservice:latest-gpu
    container_name: faster-whisper-server
    restart: unless-stopped
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "8080:9000"
    environment:
      - ASR_MODEL=medium
      - ASR_ENGINE=faster_whisper
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=0
    networks:
      - discord-bot-network
  # Alternative CPU-only version (comment out the above and uncomment below if no GPU)
  # whisper-cpu:
  #   image: ghcr.io/mutablelogic/go-whisper:latest
  #   container_name: whisper-server
  #   restart: unless-stopped
  #   volumes:
  #     - whisper_data:/data
  #   ports:
  #     - "8080:80"
  #   environment:
  #     - WHISPER_MODEL=small
  #     - WHISPER_LANGUAGE=ja
  #     - WHISPER_THREADS=4
  #   networks:
  #     - discord-bot-network

volumes:
  whisper_data:
    driver: local

networks:
  discord-bot-network:
    external: true
