name: Python Linting

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.py'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.py'
  workflow_dispatch:

jobs:
  lint-check:
    name: Check Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 isort mypy
          # Install dependencies individually to avoid conflicts
          pip install discord.py[voice]==2.3.2 sounddevice==0.4.6 numpy~=1.26.0 soundfile==0.12.1 python-dotenv==1.0.0 sqlalchemy==2.0.23 pydantic httpx aiofiles
          # Install aiavatar with --no-deps to avoid NumPy version conflict
          pip install aiavatar==0.7.2 --no-deps
      - name: Make lint script executable
        run: |
          chmod +x scripts/lint_and_fix.sh
      - name: Run linters (check mode)
        run: |
          # We set the CHANGES_MADE=false before the script,
          # then check if any changes would have been made
          ./scripts/lint_and_fix.sh --no-commit --dir=src/
          # If any Python files were modified by the script, fail the build
          if [ -n "$(git status --porcelain src/)" ]; then
            echo "::error::Linting issues found that need to be fixed. Run ./scripts/lint_and_fix.sh locally."
            git diff
            exit 1
          fi