name: Python Tests

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.py'
      - 'src/bot/requirements.txt'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.py'
      - 'src/bot/requirements.txt'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        # Install dependencies individually to avoid conflicts
        pip install discord.py[voice]==2.3.2 sounddevice==0.4.6 numpy~=1.26.0 soundfile==0.12.1 python-dotenv==1.0.0 sqlalchemy==2.0.23 pydantic httpx aiofiles
        # Install aiavatar with --no-deps to avoid NumPy version conflict
        pip install aiavatar==0.7.2 --no-deps
    - name: Install PyAudio dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y portaudio19-dev
    - name: Create .env file
      run: |
        cp src/bot/aiavatar_env.example src/bot/.env
    - name: Test with pytest
      run: |
        pytest src/bot/tests/test_ai_service.py -v